/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#400009",
        outline: "#869585",
        "surface-container-highest": "#353534",
        "primary-container": "#1db954",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary-fixed-dim": "#ffb3b3",
        "primary-fixed-dim": "#53e076",
        "on-error": "#690005",
        "surface-bright": "#393939",
        "error-container": "#93000a",
        "outline-variant": "#3d4a3d",
        "surface-container": "#201f1f",
        primary: "#53e076",
        "on-tertiary-fixed-variant": "#881d28",
        background: "#131313",
        secondary: "#c6c6c7",
        "on-primary-fixed": "#002108",
        "on-tertiary": "#680114",
        "surface-dim": "#131313",
        "inverse-primary": "#006e2d",
        "primary-fixed": "#72fe8f",
        tertiary: "#ffb3b3",
        "on-primary": "#003914",
        "tertiary-container": "#ff767b",
        "on-secondary-container": "#b4b5b5",
        "tertiary-fixed": "#ffdad9",
        "on-primary-container": "#004118",
        "secondary-fixed-dim": "#c6c6c7",
        "surface-container-high": "#2a2a2a",
        surface: "#131313",
        "on-secondary-fixed-variant": "#454747",
        "inverse-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "on-primary-fixed-variant": "#005320",
        "on-background": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#bccbb9",
        "on-error-container": "#ffdad6",
        "on-secondary": "#2f3131",
        "secondary-fixed": "#e2e2e2",
        "surface-tint": "#53e076",
        "on-tertiary-container": "#730a1b",
        "secondary-container": "#454747",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        error: "#ffb4ab",
        "inverse-on-surface": "#313030",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        unit: "8px",
        "margin-desktop": "64px",
        "container-max-width": "1000px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        display: ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        display: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0", fontWeight: "500" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};
